### ISSUE TITLE
Improve progress indicators for long-running async tasks

### ISSUE THREAD

**Issue by gayl0000** [Esri/arcgis-maps-sdk-java-samples#100]
In the reverse geocode sample, the circular progress notification could be centered, as in other samples, its not noticeable in bottom left.

In LocalServer services sample there could be a circular progress notification like other local server samples, currently you see the STARTING status, but on Linux the local server may be in this status for quite a while (10s), so other feedback might be useful.

In Local Server Geoprocessing the smaller circular progress notification is part of the mouse pointer- could it be made the same as other samples?

**Comment by tschie** [comment]
Done as part of https://github.com/Esri/arcgis-runtime-samples-java/issues/252
