### ISSUE TITLE
Importing project into Eclipse

### ISSUE THREAD

**Issue by john0005** [Esri/arcgis-maps-sdk-java-samples#171]
@tschie 
Was trying to import this project and got error below when importing as a gradle project.

Might have something to do with `sample-data` when I added that folder just under `arcgis-runtime-samples-java` it then let me pull it in as a gradle project however the `samples-data` now doesn't have anything in it. Tried deleting the `samples-data` folder once the project was imported and nothing happened. Didn't throw an error or create the `samples-data` folder.

**Comment by john0005** [comment]
For now I am just going to add the samples data in for myself and I believe that should be it working till this gets looked at.

**Comment by john0005** [comment]
![screen shot 2017-07-13 at 11 44 54 am](https://user-images.githubusercontent.com/14575538/28163752-5d54c582-67c4-11e7-9399-afb7ffe6b164.png)

**Comment by john0005** [comment]
This worked fine for me on Windows. Just Mac gave me a problem.

**Comment by tschie** [comment]
@john0005 The gradle issue shouldn't have anything to do with the samples-data. 

For the samples data issue: You shouldn't have to add that folder yourself. You should just refresh the project and the samples-data folder should download with all the data. If you make the folder yourself, the gradle task will see the folder and assume it's already downloaded, so it won't redownload the data. Try deleting the folder and refreshing the project.

For the gradle issue: I've seen this before with Eclipse. I will look into it. As a workaround, try deleting the gradle folder and wrapper files before importing.
