### ISSUE TITLE
Portal: samples can be updated using Default Authentication

### ISSUE THREAD

**Issue by john0005** [Esri/arcgis-maps-sdk-java-samples#173]
@tschie Any portal sample that is using the custom `AuthenticationDialog` can be updated to use `DefaultAuthentication` now.

Once issues below are done this will be in master:
  - https://devtopia.esri.com/runtime/java-se-api/issues/2387
  - https://devtopia.esri.com/runtime/java-se-api/issues/2389

Note: 
I can see how showing how to use Default Authentication can be a good thing but I also see how showing someone how to make their own is also a good thing. Maybe we don't have all samples change to DefaultAuthentication?

**Comment by john0005** [comment]
This is on master now.

**Comment by tschie** [comment]
Yeah we should change the non-oauth ones to use DefaultAuthentication.

**Comment by tschie** [comment]
At this point, I think we should just use DefaultAuthentication for new samples and leave the old ones as is.
