### ISSUE TITLE
Is there a size limitation of mobile map package for opening in App studio. 

### ISSUE THREAD

**Issue by AhmedTambe** [Esri/arcgis-maps-sdk-java-samples#229]
Created a mobile map package (size 10 MB)--> Opens fine in App Studio.

Created a mobile map package (size 1.2 GB)--> Does not open in App Studio, no errors (Only blank screen).

Is there any other application apart from AppStudio, which i could try and further narrow down the issue?

**Comment by tschie** [comment]
Hi @AhmedTambe I don't think this question is very well suited for this repo. You will probably have better luck posting this question on [GeoNet](https://community.esri.com/). That said, I asked around and was told there shouldn't be a limit. You could try to open it based on this sample https://github.com/Esri/arcgis-runtime-samples-java/tree/master/src/main/java/com/esri/samples/map/open_mobile_map_package if you are familiar with the Java SDK. I don't know if that will help you understand the issue with Android Studio though. Unfortunately, if the question isn't related to the Java SDK, I probably won't be able to help you. Best of luck.
