### ISSUE TITLE
Update style file

### ISSUE THREAD

**Issue by john0005** [Esri/arcgis-maps-sdk-java-samples#251]
@tschie 

Seem we need to update the style.css file. I am realizing that all the controls look disabled.

**Comment by john0005** [comment]
![screen shot 2018-06-13 at 9 45 20 am](https://user-images.githubusercontent.com/14575538/41365774-2b9e8770-6eef-11e8-9090-23fd700f8cb6.png)

**Comment by tschie** [comment]
@john0005 I added a fix in the dev and 100.3.0 branches. Can you please verify?

**Comment by tschie** [comment]
Hmm, looks like that didn't actually work. I'll keep trying.

**Comment by tschie** [comment]
@john0005 Please check this again. I think it should actually be fixed now.

**Comment by john0005** [comment]
Looks good!
