### ISSUE TITLE
Adding Progress Indicator

### ISSUE THREAD

**Issue by john0005** [Esri/arcgis-maps-sdk-java-samples#252]
These samples should add a Progress Indicator. Sometimes when I run them I think they are broke because it takes a little bit to load.

- [WMS Layer](https://github.com/Esri/arcgis-runtime-samples-java/tree/master/src/main/java/com/esri/samples/ogc/wms_layer_url)
- [Raster Function](https://github.com/Esri/arcgis-runtime-samples-java/tree/master/src/main/java/com/esri/samples/raster/raster_function)
- [Raster Layer](https://github.com/Esri/arcgis-runtime-samples-java/tree/master/src/main/java/com/esri/samples/raster/raster_layer_url)

**Comment by tschie** [comment]
I added one for WMS. The raster samples load fairly quickly for me. Also, their delay isn't caused by loading, instead it's the raster rendering which is a little more difficult to attach a progress indicator to.
