### ISSUE TITLE
Error in mapLocation

### ISSUE THREAD

**Issue by deerob** [Esri/arcgis-maps-sdk-java-samples#35]
Error i found is: Could not find or load
main class SetInitialMapLocation

**Comment by doneill** [comment]
@deerob Can you provide more context into the steps you took to get that error?  What platform are you using?

**Comment by deerob** [comment]
hi
I imported the project as gradle using Eclipse Committers Mars, I also installed the buildship Eclipse Gradle plugin and the ArcGIS runtime SDK. compiled and ran i tried to fix error but still working on it.

**Comment by doneill** [comment]
@deerob Are you still having issues?  Beyond installing, how are you invoking the gradle commands?  Through Eclipse plugin or command line?

**Comment by doneill** [comment]
@deerob We just released beta-2 samples with improved integration with gradle through our gradle plugin.  I encourage you to try this and any other sample and provide feedback.  I am going to close this issue as we have a new release and workflow, please feel free to re-open if you encounter the issue in the latest release.
