### ISSUE TITLE
Bad metadata file

### ISSUE THREAD

**Issue by ChrisFrenchPDX** [Esri/arcgis-maps-sdk-java-samples#410]
Hey @tschie - this [metadata file](https://github.com/Esri/arcgis-runtime-samples-java/blob/master/map/create-and-save-map/README.metadata.json) lists `src/main/java/com/esri/samples/create_and_save_map/OAuthChallengeHandler.java` as a code file, but it's missing here: https://github.com/Esri/arcgis-runtime-samples-java/tree/master/map/create-and-save-map/src/main/java/com/esri/samples/create_and_save_map. 

Is there a missing file or is the metadata file incorrect?

cc @jf990 @mikewilburn

**Comment by tschie** [comment]
We used to have a custom OAuth handler. In the last release, we removed it to use the default. The file should not be in the snippet list.

**Comment by tschie** [comment]
I've just made the change.

**Comment by ChrisFrenchPDX** [comment]
> I've just made the change.

Awesome, thank you @tschie!

**Comment by ChrisFrenchPDX** [comment]
Verified.
