### ISSUE TITLE
When building build.gradle could not find apiKey system property even though the apiKey is in the gradle.properties filr

### ISSUE THREAD

**Issue by tuckers1967** [Esri/arcgis-maps-sdk-java-samples#641]
I had to manually insert the api key to get sample (com.esri.samples.add_graphics_with_renderer) to run. If I just update the HOME\.gradle\gradle.properties file to something like

apiKey = apiKey

where the apiKey is a valid key. When I try and use the run gradle task I get

Execution failed for task ':run'.
> Could not get unknown property 'apiKey' for task ':run' of type org.gradle.api.tasks.JavaExec.

Hopefully its just something I am doing wrong.

I am using Intellij on windows 10.

**Comment by Rachael-E** [comment]
hi @tuckers1967, try running the `createGradlePropertiesAndWriteApiKey` task separately before running the `run` task: that should then set a System Property on your computer for `apiKey` and then read the apiKey value from the gradle.properties file. It sounds like the System Property hasn't been created when running the sample. How were you running the sample: was it via the IntelliJ IDE gradle task window?

**Comment by tuckers1967** [comment]
Hi, thanks for replying. I have run the createGradlePropertiesAndWriteApiKey task separtaly. The gradle.properties file already existed with the apiKey property. I run the sample using IntelliJ IDE using the gradle run task. I still get the error.

Execution failed for task ':run'.
> Could not get unknown property 'apiKey' for task ':run' of type org.gradle.api.tasks.JavaExec.

**Comment by Rachael-E** [comment]
it could be your machine isn't finding the gradle.properties file, and so it's failing to set the system property as specified in the gradle script. It should be in the following location:

Mac
```
/Users/username/.gradle/gradle.properties
```

and on Windows:
```
C:\Users\username\.gradle\gradle.properties
```

it's possible your machine is finding a different .gradle directory or gradle.properties file and looking in there and failing to find the `apiKey` key. gradle.properties should look like the following:

```
apiKey = 123456789apikeyabcdefgh
``` 

If that doesn't resolve it, I'd try removing the repo from your machine, and repulling it, reload all gradle projects, and try that again. Let us know how you get on!

**Comment by tuckers1967** [comment]
Hi,

Ok I got it working many thanks. I needed to point IntelliJ  to where the gradle properties file is. That did the trick. Thanks for your support.

**Comment by Rachael-E** [comment]
glad you got it working: thanks for the feedback on this!
